CREATE TABLE Usuarios (
    UsuarioID INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    CorreoElectronico VARCHAR(100) NOT NULL,
    Contraseña VARCHAR(50) NOT NULL,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

-- Stored Procedure para Registro de Usuarios
CREATE PROCEDURE RegistrarUsuario
    @Nombre VARCHAR(50),
    @CorreoElectronico VARCHAR(100),
    @Contraseña VARCHAR(50)
AS
BEGIN
    INSERT INTO Usuarios (Nombre, CorreoElectronico, Contraseña)
    VALUES (@Nombre, @CorreoElectronico, @Contraseña)
END;

------------------------------
CREATE TABLE QuichePalabrasFrases (
    PalabraFraseID INT PRIMARY KEY IDENTITY(1,1),
    PalabraFraseQuiche NVARCHAR(255) NOT NULL,
    TraduccionEspañol NVARCHAR(255) NOT NULL,
    FechaAgregacion DATETIME DEFAULT GETDATE(),
    UsuarioID INT,
    CONSTRAINT FK_Usuario_PalabraFrase FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)
);

-- Trigger para Registro de Nuevas Palabras o Frases
CREATE TRIGGER RegistroPalabraFrase
ON QuichePalabrasFrases
AFTER INSERT
AS
BEGIN
    INSERT INTO EstadisticasPalabras (Palabra, CantidadConsultas, FechaEstadistica)
    SELECT i.TraduccionEspañol, 0, GETDATE()
    FROM inserted i
    WHERE NOT EXISTS (
        SELECT 1
        FROM EstadisticasPalabras
        WHERE Palabra = i.TraduccionEspañol
    )
END;

-------------------------

CREATE TABLE Consultas (
    ConsultaID INT PRIMARY KEY IDENTITY(1,1),
    UsuarioID INT,
    TextoConsulta NVARCHAR(MAX) NOT NULL,
    FechaConsulta DATETIME DEFAULT GETDATE(),
    IP VARCHAR(15), -- Suponiendo que la IP es almacenada en formato de texto
    CONSTRAINT FK_Usuario_Consulta FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)
);

------------------------

CREATE TABLE NoEncontradas (
    NoEncontradaID INT PRIMARY KEY IDENTITY(1,1),
    PalabraFrase NVARCHAR(255) NOT NULL,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

-----------------------------------------

CREATE TABLE EstadisticasPalabras (
    EstadisticaID INT PRIMARY KEY IDENTITY(1,1),
    Palabra NVARCHAR(255) NOT NULL,
    CantidadConsultas INT NOT NULL,
    FechaEstadistica DATETIME DEFAULT GETDATE()
);

-- Stored Procedure para Registrar Consulta y Actualizar Estadísticas
CREATE PROCEDURE RegistrarConsulta
    @UsuarioID INT,
    @TextoConsulta NVARCHAR(MAX),
    @IP VARCHAR(15)
AS
BEGIN
    INSERT INTO Consultas (UsuarioID, TextoConsulta, IP)
    VALUES (@UsuarioID, @TextoConsulta, @IP)

    UPDATE EstadisticasPalabras
    SET CantidadConsultas = CantidadConsultas + 1
    WHERE Palabra IN (SELECT TraduccionEspañol FROM QuichePalabrasFrases WHERE @TextoConsulta LIKE '%' + PalabraFraseQuiche + '%')
END;


----------------------insertar datos en tabla diccionario---

INSERT INTO QuichePalabrasFrases (PalabraFraseQuiche, TraduccionEspañol, UsuarioID)
VALUES
	('A',	'Muchacho, niño', 1),
	('Ab’',	'Hamaca',1),
	('Ab , ch’at',	'Catre',1),
	('Ab’a’q',	'Hollín',1),
	('Ab’a’qchiköp', 'Milpiés',1),
	('Ab’aj', 'Piedra',1), 
	('Ab’äj', 'Mineral',1), 
	('Ab’ix','Milpa',1),
	('Achalal', 'Pariente, familiar',1), 
	('Achalalib’al','Hermanastro (a)',1), 
	('Achalalil k’aslemal','Vida familiar',1), 
	('Achalalxik', 'Parientes',1), 
	('Achalka’n', 'Concuña',1), 
	('Achb’anoj','Adverbio',1),
	('Achb’axininem', 'Tira cómica',1), 
	('Achb’i’aj, q’alajsab’äl b’i’aj', 'Adjetivo',1), 
	('Acheqa’lenel', 'Paciente',1),
	('Achi','Hombre',1), 
	('Achi k’ulajil', 'Homosexual',1), 
	('Achi’al', 'Masculino',1),
	('Achi’l', 'Amigo',1), 
	('Achi’lanel', 'Escolta',1), 
	('Achi’lanem', 'Afiliado',1),
	('Achi’lib’', 'Compadres',1), 
	('Achib’il', 'Compañero (a), amigo (a)',1), 
	('Achib’ilanik, achib’ilanem', 'Acompañar',1),
	('Achijal', 'Masculino',1),
	('Achijil',	'Esposo',1), 
	('Achik’', 'Visión',1),
	('Achik’al tijonem', 'Educación virtual',1), 
	('Achik’anem', 'Soñar, fantasia',1),
	('Achik’nem', 'Imaginación',1), 
	('Achikowija’', 'Semen',1), 
	('Achixanik, achixanem', 'Celar',1),
	('Achixik',	'Celoso',1), 
	('Achji’','Concuño',1),
	('Achochib’äl', 'Dirección',1), 
	('Achochib’äl',	'Hábitat',1),
	('Africa', 'África',1), 
	('Africano', 'Africano',1),
	('Aj', 'Elote, cohete, caña de carrizo',1), 
	('Aj ab’yayala', 'Americano',1),
	('Aj eta’mab’alil k’aslem',	'Biólogo',1),
	('Aj Europa', 'Europeo',1), 
	('Aj Francia', 'Francés',1),
	('Aj il', 'Responsable',1), 
	('Aj Italia', 'Italiano',1),
	('Aj jela’ ch’awem', 'Lengua extranjera',1), 
	('Aj paxil kayala’', 'Guatemalteco',1),
	('Ajalib’äl', 'Factor',1), 
	('Ajalk’walib’äl', 'Adopción',1),
	('Ajanel', 'Carpintero',1), 
	('Ajatz’yaqb’äl', 'Modista',1), 
	('Ajaw,ajawaxel', 'Dios',1),
	('Ajawan ib’ xoqoje’ k’utb’alil', 'Género y autoestima',1), 
	('Ajawb’äl', 'Reino',1),
	('Ajb’anal kaxlanwa', 'Panadero',1), 
	('Ajb’anal wa',	'Cocinero (a)',1), 
	('Ajb’insal ch’ich’', 'Chofer',1), 
	('Ajch’ab’äl', 'Católico',1),
	('Ajch’aqaja’ b’antajik', 'Cultura Occidental',1), 
	('Ajch’umil', 'Astrónomo',1), 
	('Ajcha’al q’ayes', 'Botánico',1),
	('Ajchajil re tinimit',	'Policía, soldado',1),
	('Ajchak', 'Profesional',1), 
	('Ajchaq’e chak', 'Patrón',1),
	('Ajchomsu’', 'Trompetista',1),
	('B’a', 'Taltuza',1),
	('B’ajb’äl', 'Martillo',1), 
	('B’ajinik, b’ajinem', 'Clavar',1), 
	('B’alam', 'Jaguar, tigre',1), 
	('B’alkatinem, b’alkatinik', 'Rodar',1),
	('B’aluk', 'Cuñado de hombre',1), 
	('B’anb’äl', 'Molde',1),
	('B’anb’äl chulaj', 'Letrina',1),
	('B’anb’äl chuluj',	'Servicio sanitario',1),
	('B’anb’äl k’ajkab’', 'Ingenio',1),
	('B’anb’äl taqanib’äl', 'Congreso',1), 
	('B’anb’äl wa', 'Cocina',1), 
	('B’anb’alnik', 'Moldear',1), 
	('B’anbäl no’jwuj', 'Imprenta',1), 
	('B’anem', 'Predicado',1), 
	('B’anik, b’anonem, b’anonik', 'Hacer',1), 
	('B’anikil', 'Identidad',1),
	('B’anikil', 'Posicional',1), 
	('B’ankoyuq ch’ich’', 'Niobio',1),
	('B’anoj', 'Verbo',1), 
	('B’anojil', 'Verbal',1),
	('B’anöl taqanik', 'Diputado',1), 
	('B’anol tzij', 'Mentiroso',1), 
	('B’anom', 'Hecho B’anom','Artificial',1),
	('B’anom uk’u’xjastaq','Tecnecio',1), 
	('B’anowem','Acción',1),
	('B’antajik','Drama (obra de teatro)',1), 
	('B’antajik','Dignidad',1),
	('B’antajik b’anikil', 'Identidad cultural',1), 
	('B’antajik no’jk’aslemal','Valores culturales',1), 
	('B’antajik, wokaj k’aslemal','Cultura',1),
	('B’antajinik, kab’antajinik', 'Dramatizar,dramatiza',1), 
	('B’anub’eyal ilwäch','Óptico',1),
	('B’anyal','Pragmatismo',1),
	('B’aq','Aguja, delgado, hueso',1), 
	('B’aq etz’b’äl','Dado',1),
	('B’aq k’amatyo’jil','Tejido óseo',1), 
	('B’aq q’otz','Pómulo',1),
	('B’aq’tim tz’ib’awuj','Cuaderno de espiral',1), 
	('B’aqil k’ajk’äs','Citoesqueleto',1),
	('B’aqil, ch’akul','Cuerpo',1),
	('B’aqilal','Esqueleto, vertebrado',1), 
	('B’aqilno’j', 'Paradigma',1),
	('B’aqiltzib’','Consonante',1),
	('B’aqonem, b’och’onem, b’aqonik','Restregar, frotar',1),
	('B’aqonik','Frotar, restregar',1), 
	('B’atz’','Hilo (de algodón)',1), 
	('B’atz’im','Hilado',1), 
	('B’atz’inem, b’atz’inik','Hilar',1),
	('B’atz’om kamnaq','Momia',1), 
	('B’e','Camino',1),
	('B’ek','Ir',1), 
	('B’elejeb’','Nueve',1),
	('B’elejk’al','Ciento ochenta',1), 
	('B’elejlajk’al','Trescientos ochenta',1), 
	('B’elejlajq’o’','Siete mil seiscientos',1), 
	('B’elejlajuj','Diecinueve',1), 
	('B’elejq’o’','Tres mil seiscientos',1), 
	('B’enaq q’ij','Tarde',1),
	('B’enaq q’ij, uqajib’al q’ij','Atardecer',1), 
	('B’etz’ib’','Ortografía',1),
	('B’eyajel, q’axel, ajch’aqaja’','Extranjero, forastero',1), 
	('B’eyajem, b’eyajik','Viajar, pasear',1),
	('B’eyal k’u’xchak','Método de síntesis',1), 
	('B’eyal rech tijonik','Método de enseñanza',1),
	('B’eyal reta’maxik tzijonem','Método de aprendizaje de idiomas',1),
	('B’eyal ruk’utik ukab’ ch’ab’äl','Método para la enseñanza de segunda lengua',1),
	('B’eyal sik’itz’ib’anem','Métodos de lectoescritura',1), 
	('B’eyal solwäch','Método de análisis',1),
	('B’e’al tijonik, b’eyal','Método',1), 
	('B’e’n','Enano',1),
	('B’e’nche’','Arbusto',1),
	('B’eelom','Marido, esposo',1), 
	('B’ijna’oj','Predicativo',1), 
	('B’ijnem','Sugerencia',1), 
	('B’ijnik','Sugerir',1),
	('B’iloj, rax kinaq’','Ejote',1), 
	('B’inäl tzij',	'Semántica',1), 
	('B’inem juyub’','Alpinismo',1), 
	('B’inem, b’inik','Caminar',1), 
	('B’insanel ch’ich’','Piloto',1),
	('B’insanem','Trámite',1),
	('B’iq’b’anel silowäch','Camarógrafo (de tele)',1), 
	('B’iq’onem','Tragado',1),
	('B’iq’onem b’iq’onik','Tragar',1),
	('B’iq’silowachib’äl','Cámara de video, de televisión',1), 
	('B’iq’wachib’äl','Cámara digital',1),
	('B’iqonem','Desgranando',1), 
	('B’iqonik, b’iqonem','Desgranar',1),
	('B’irb’itq’ajaj', 'Onda sonora, onda acústica',1), 
	('B’irirtab’äl, xelayil','Tímpano',1),
	('B’isonem','Triste',1), 
	('B’itok, ilb’äl, okib’al saq','Ventana',1),
	('B’ix','Canción, canto',1), 
	('B’ixajaw','Alabanza',1),
	('B’ixal','Melodía',1), 
	('B’ixb’äl','Cancionero',1),
	('B’ixik','Decir',1),
	('B’ixkil','Informe, Informativo',1), 
	('B’ixonel','Cantante',1),
	('B’ixonik','Cantar',1),	
	('B’i’aj','Nombre',1), 
	('B’i’aj, b’i’ajnem','Sustantivo',1),
	('B’i’ajnel','Sustantivizador',1), 
	('B’i’ajnem','Sustantivos',1), 
	('B’i’nik','Nombrar',1), 
	('B’ochk’ulajil','Noviazgo',1), 
	('B’oko’','Chimaltenango',1),
	('B’okob’, tatb’em','Escudo',1),
	('B’ol, xax ch’ich’','Lata',1), 
	('B’olaj','Trozo',1),
	('B’olajch’ich’, yuquyik ch’ich’','Ferrocarril',1),
	('B’olb’äl','Rodillos',1), 
	('B’olb’ik, b’olob’il','Cilíndrico',1),
	('B’olob’ik','Cilindro',1),
	('Cha’b’äl','Filtro (de aceite)',1),
	('Cha’b’äl chäj','Filtro (para pantalla de computadora',1), 
	('Cha’nel','Jurado',1),
	('Cha’tältijonem','Educación no Formal',1), 
	('Cha’yinik, kchayinik','Votar, vota',1),
	('Chab’äl','Coladera',1), 
	('Chab’ana jun toq’ob’','Por favor',1),
	('Chab’ij chwe','Decímelo',1),
	('Chachal','Collar',1),
	('Chaj','Gris, cenizo, ceniza, ocote, pino',1), 
	('Chajim q’ij','Feriado',1),
	('Chajinb’äl yawab’','Enfermería',1), 
	('Chajinel','Policía',1),
	('Chajinel amaq’','Ejército, soldado',1), 
	('Chajinel yawab’, ajyab’','Enfermera',1), 
	('Chajinik','Cuidar, proteger',1), 
	('Chajinsanem','Cremación',1),
	('Chajitalil, jikomal','Seguridad',1),
	('Chajnel','Fósforo (como elemento)',1), 
	('Chak','Trabajo',1),
	('Chak chuqe kamulinem','Actividades y ejercicios',1), 
	('Chak wokajtaqanik','Legislación laboral',1), 
	('Chak xuquje’ tikojilil','Trabajo y productividad',1), 
	('Chak’amalo chwe','Tráemelo',1),
	('Chakach','Canasta',1), 
	('Chakäch potz’','Baloncesto',1),
	('Chakäch, ch’uy, ch’ajo’n','Mechón (como de jirafa)',1), 
	('Chakalb’äl ch’ich’','Parqueo',1),
	('Chakub’äl','Útiles de trabajo, herramientas',1), 
	('Chakunel','Profesional',1),
	('Chakunem','Profesionalidad',1), 
	('Chakunib’äl','Instrumental',1), 
	('Chakunik','Trabajar',1), 
	('Champomanel nab’e ajpop, k’amöl b’e amaq’','Presidente de república',1), 
	('Chanim tz’ib’','Taquigrafía',1),
	('Chanim, aninaq','Pronto',1), 
	('Chapab’äl q’ab’','Anticipo',1), 
	('Chapanik, k’osk’otik','Tocar',1), 
	('Chapatalik','Detenido',1),
	('Chapb’äl, tiqchapab’äl','Gancho (de ropa)',1),
	('Chapik, chaponik, chaponem','Agarrar, tocar',1), 
	('Chapob’al, lajab’','Trampa',1), 
	('Chaponem','Agarrarlo',1),
	('Chaq’, nuchaq’','Hermana menor de mujer',1), 
	('Chaq’ajnaq','Cocido',1),
	('Chaq’ajrsan, tzakik','Cocer, cocido',1),
	('Chaq’ich’umil','Neptuno (planeta)',1),
	('Chaqi’j','Seco',1),
	('Chaqi’j chikop','Insecto',1), 
	('Chaqi’jarem, chaqi’jarik','Secar',1), 
	('Chaqi’jb’äl','Deshidratante',1), 
	('Chaqi’jnem','Deshidratación',1), 
	('Chaqi’jnik','Deshidratar',1), 
	('Chaqi’jq’ijol','Otoño',1),
	('Chaqo’n','Ordinario (tosco, burdo)',1), 
	('Chaqon','Cosquilla',1),
	('Chaqonanem, chaqonanik','Hacer cosquillas',1), 
	('Chareb’äl','Carruaje',1),
	('Charqajin ib’','Aterrizarse (de aviones, helicópteros)',1), 
	('Charqajinem','Aterrizaje',1),
	('Charqajinik','Aterrizar',1),
	('Charyak ib’','Despegarse (de aviones, etc.)',1), 
	('Charyakinik','Despegar',1),
	('Chasacha numak','Perdóname, discúlpame',1),
	('Chatäl wa’im','Dieta',1), 
	('Chatwaljoq','Levántese',1), 
	('Chawila awib’','Cuídate',1), 
	('Chayunik, chayunem','Colar',1),
	('Che’','Árbol,madera, palo',1),
	('Che’ tz’ib’ab’äl','Lápiz',1),
	('Che’tz’ajb’äl','Crayón de madera',1), 
	('Che’wkaq’iq’il','Troposfera',1),
	('Chet','Granero cuadrado',1), 
	('Chetechik','Plegado',1),
	('Chi la’','Allí',1),
	('Chi pur','Jutiapa',1), 
	('Chi rech','A él, ella',1), 
	('Chi rij',	'A tras de',1), 
	('Chi’aj','Boca',1), 
	('Chi’ch’, kupib’al, qupib’äl, pusb’äl','Cuchillo',1), 
	('Chi’ychïk','Fleco',1), 
	('Chib’, chib’cha’q','Helecho',1), 
	('Chij','Lana',1),
	('Chikb’äl ja’, sutz’b’äl ja','Rociador (spray',1),
	('Chikop, awaj','Animal, animal doméstico',1), 
	('Chikopb’äl','Zoológico, jardín zoológico',1), 
	('Chikopil','Parásito',1),
	('Chikopk’ajnem','Polinización entomógama (por insectos)',1),
	('Chilb’ejnem, chilb’ej','Exhortación, exhortar',1), 
	('Chim','Morral, bolsa, matate',1), 
	('Chimchikopib’	Marsupiales Chinab’jul','Huehuetenango',1), 
	('Chipaxukut, jeqxukut','Lado inicial',1),
	('Chipnem, majb’äl , jeqb’äl','Inicio',1), 
	('Chiq’ayes','Zacapa Chiquimula	Chiquimula',1),
	('Chirij kolonel','D.c.(después de cristo)',1), 
	('Chirij','le, Afuera de',1),
	('Chirij, k’a te k’u ri’','Después, detrás de',1), 
	('Chirijja’j','Velo (paladar suave)',1), 
	('Chirijset','Metasfera',1),
	('Chirmi’y, su’','Chirimía',1), 
	('Chitatab’ej ak’alab’','Atención niños',1), 
	('Chitatb’ej','Escuchen',1), 
	('Chitzapij ichi, kixch’aw taj','Silencio',1),
	('Cho','Lago',1), 
	('Cho’kej, kumatz','Calambre',1),
	('Cho’l, jolojik, tuqutik','Flojo (ropa floja)',1), 
	('Cho’m','Camarón',1),
	('Cho’pijat’inib’äl','Desarmador (destornillador)',1),
	('Cho’pinik','Desenroscar',1), 
	('Chojjäb’','Diluvio',1), 
	('Chojoj atinib’äl','Ducha',1), 
	('Chok’ok’, pok’opik','Tieso',1), 
	('Chokoyab’äl','Formulario',1), 
	('Chokoyam','Formulado',1), 
	('Chokoyanem','Formulación',1), 
	('Chokoyanik','Formular',1), 
	('Chokoyil','Fórmula',1),
	('Chol','Tabla (matemática o elementos básicos químicos)',1), 
	('Cholaj','Fila, hilera',1), 
	('Cholajil saqil','Receta',1),
	('Cholajilab’äl','Sistema de numeración',1), 
	('Cholajilanik','Contabilidad',1),
	('Cholb’äl chak','Programa',1), 
	('Cholb’äl tzij','Crucigrama',1), 
	('Cholb’inem','Desfile',1), 
	('Cholchak','Plan',1),
	('Cholchak tijonem, cholchakunik','	Planificación educativa, planificar',1), 
	('Cholchi’','Comunidad lingüística',1), 
	('Choletz’anem','Deporte',1),
	('Choljik’nem, ub’ek’i’alil','Ecuación',1), 
	('Cholk’aslemal','Constitucionalidad',1),
	('Cholk’utub’äl pam','Tabla de contenidos',1), 
	('Cholkejen ch’ich’','Ciclismo',1),
	('Cholkunel','Receta de comida',1), 
	('Cholkunub’al','Receta de medicamento',1), 
	('Cholöl tzij','Sintaxis',1),
	('Chololej','Ordenar',1), 
	('Cholpaxnel','Múltiplo',1),
	('Cholq’ax','Programa (radiofónico)',1),
	('Cholq’ax silowäch','Programa (programa de televisión)',1), 
	('Cholq’axnem','Programación (de televisión)',1), 
	('Cholse’tb’ix','Discoteca',1),
	('Choltijomb’äl','Currículo',1), 
	('Choltijonem','Educación formal',1), 
	('Choltz’ib’','Alfabeto',1), 
	('Choltz’ib’alil','Alfabetismo',1), 
	('Choltz’ib’anem, eta’man tz’ib’anik’','Alfabetización',1), 
	('Choltz’ib’anik','Alfabetizar',1), 
	('Choltzij, cholsuk’tzij, soltzij','Diccionario',1), 
	('Choluk’u’x chulb’äl','Sistema urinario',1), 
	('Choluk’u’x ib’och’ib’äl','Sistema nervioso',1),
	('Choluk’u’x kik’el','Sistema circulatorio',1), 
	('Choluk’u’x uxlab’al','Sistema respiratorio',1), 
	('Choluk’u’x wa’ikil','Sistema digestivo',1), 
	('Cholupam','Contenido',1),
	('Cholwachb’äl','Álbum',1), 
	('Chom','Gordo',1), 
	('Chom nakalwos	Xenón Chom su’, kaxla’n su’','Trompeta',1), 
	('Chomab’äl','Política',1),
	('Chomab’äl tzij','Política,lingüística',1), 
	('Chomanem','Pensamiento',1), 
	('Chomanik','Pensar',1), 
	('Chomwiq’ab’','Dedo pulgar',1), 
	('Chomxko’l','Intestino grueso',1), 
	('Choqoje’, xuquje’','También',1), 
	('Choyib’al','Machete',1),
	('Choyoj ajij','Zafra',1),
	('Chu','Hediondo',1), 
	('Chu wach','Ante',1), 
	('Chu’ab’äj','Azufre',1), 
	('Chub’, nuchub’','Saliva',1), 
	('Chub’aj','Escupo',1), 
	('Chub’anem, chub’anik, chub’nik','Escupir',1), 
	('Chuch, nan','Mamá',1), 
	('Chuchi’','A la orilla de',1),
	('Chuchuxel','Señora principal',1), 
	('Chul ib’ ch’ich’','Estroncio',1),
	('Chulaj','Orina, miado',1),
	('Chulb’al K’ajk’äs','Aparato de Golgí',1), 
	('Chun','Cal',1),
	('Chupam','Adentro, dentro',1), 
	('Chupb’äl q’aq’','Extintor',1), 
	('Chupb’äl tz’ib’','Corrector',1),
	('Chupch’umil','Nova (astronomía)',1), 
	('Chupchutik ab’äj','Perla',1),
	('Chuplib’äl','Flash',1), 
	('Chupulq’aq’','Luciérnaga',1), 
	('Chupum','Apagado',1), 
	('Chupunem','Cesación',1), 
	('Chupunik, chupunem','Apagar',1),
	('Chuq’ab’ k’amaq’aq’','Resistencia eléctrica',1), 
	('Chuq’ab’il','Energía',1),
	('Chuq’ab’il ulew','Abono',1), 
	('Chuq’ab’iwa, yab’äl chuq’ab’il','Vitamina',1), 
	('Chuq’akik’el','Presión arterial',1),
	('Chutzal, chuxukut','Al lado de..., al reverso',1), 
	('Chuwach','Enfrente de',1),
	('Chuxe’','Debajo de ',1),
	('Chuxo’','Entre',1), 
	('Chuxukut, naqaj','Cerca de, cerca',1), 
	('Chwe’q	','Mañana',1), 
	('Chwimeq’ena’','Totonicapán',1),
	('E are’','Ellos, ellas',1),
	('Echam','Cuñado de mujer',1),	
	('Echanel, echanik','Poseedor, poseer',1), 
	('Echb’äl amaq’','Patria',1),
	('Echkil','Egocentrismo',1),
	('Ek’','Pie de gallo, pata de gallo',1), 
	('Elaq’än wach','Piratería',1),
	('Elaq’om','Asaltante',1), 
	('Elem, elik','Salir',1),
	('Elesanem, elesanik, esaxik','Eliminar, quitar, sacar',1), 
	('Elik','Deserción',1),
	('Elk’ayij','Exportar',1), 
	('Elunimrisanem','Internacional',1), 
	('Elunimrisaxik','Internacionalizar',1),
	('Ema','Pero',1), 
	('Eqa’lenel','Agente',1), 
	('Eqa’n','Carga',1), 
	('Eqale’n, chak','Oficio, cargo',1), 
	('Eqanib’äl','Mochila',1), 
	('Eqanib’äl ch’ich’','Camión',1),
	('Eqanik, eqanem','Cargar (en la espalda)',1), 
	('Erab’äl ja’','Cubeta',1),
	('Ereb’äl','Flete',1), 
	('Erenem','Acarréalo',1), 
	('Erenik, erenem','Acarrear',1), 
	('Esab’äl wachb’äl','Cámara',1),
	('Esalitzelatz’am','Plomo (elemento químico)',1),
	('Esanem','Menos',1),
	('Esanem, k’amoj','Sustracción',1), 
	('Esb’äl no’j','Experimento',1), 
	('Esb’äl sïb’','Chimenea',1),
	('Estados Unidos de América','Estados Unidos de América',1), 
	('Eta’mab’äl','Conocimiento',1),
	('Eta’mab’alil b’antzij','Lingüística aplicada',1), 
	('Eta’mab’alil ja','Hidrología',1), 
	('Eta’mab’alil jalwajastäq','Física',1),
	('Eta’mab’alil k’aslem','Biología',1), 
	('Eta’mab’alil kab’raqan','Sismología',1),
	('no’jb’anem','Ciencias Naturales y Tecnología',1),
	('Eta’mab’alil kunub’äl','Farmacología',1),
	('Eta’mab’alil suqyab’il','Epidemiología',1), 
	('Eta’mab’alil tz’aqatil jastaq','Química',1), 
	('Eta’mab’alil uwachulew','Geografía',1), 
	('Eta’mab’alil uxe’yab’il','Patología',1), 
	('Eta’mab’alil winaqil','Sociología',1), 
	('Eta’mab’alil winaqilal','Ciencias sociales',1), 
	('Eta’mab’alil winaqilitzij','Sociolingüística',1), 
	('Eta’mab’alil xkanul','Vulcanología',1), 
	('Eta’mab’alil yab’anima’','Cardiología',1),
	('Eta’makab’raqanel','Sismólogo',1), 
	('Eta’malil q’ab’ch’ab’äl','Dialectología',1), 
	('Eta’manem, janik’','Saber',1),
	('Eta’manik nuk’soltzij','Lexicologia',1),
	('Eta’manik, eta’manem','Aprender a aprender, conocer, saber',1), 
	('Eta’mariqonem','Competencias cognoscitivas',1), 
	('Eta’mb’alil chikopib’','Zoología',1),
	('Eta’mb’alil no’j','Psicología',1), 
	('Eta’mb’alil puqno’jib’äl','Ingeniería',1), 
	('Eta’mb’anik','Saber actuar',1), 
	('Etab’äl','Medida',1),
	('Etab’äl rech jastäq','Evaluación de productos',1),
	('Etab’äl jech’b’alil','Estadística',1), 
	('Etab’äl q’aq’al','Termómetro',1), 
	('Etab’al q’ij, kajb’alil','Horario',1), 
	('Etab’äl, etab’äl eta’manik','Evaluación',1), 
	('Etab’anik','Evaluar',1),
	('Etab’anik ri b’ijno’j eta’manik','Evaluar el conocimiento conceptual',1), 
	('Etab’anik ri no’jib’äl eta’manik','Evaluar el conocimiento actitudinal',1), 
	('Etab’anik ri q’axno’j eta’manik','Evaluar el conocimiento procedimental',1), 
	('Etabäl rech q’axnem','Evaluación de procesos',1),
	('Etal	Señal, huella',1), 
	('Etal','Símbolo',1),
	('Etal','Código',1),
	('Etal k’olompwaq','Cuenta de ahorros',1), 
	('Etal pwaqb’äl','Cuenta bancaria',1), 
	('Etal tzij','Código lingüístico',1), 
	('Etalil','Simbolismo',1),
	('Etan ib’','Autoevaluación',1), 
	('Etanem, etanik','Medir',1),
	('Etanib’äl b’anoj','Reglamento',1), 
	('Etawosb’äl','Barómetro',1), 
	('Etb’äl roqow','Ebullómetro',1), 
	('Etok’al','Metro (medida)',1), 
	('Etpaqalib’äl','Altímetro',1), 
	('Etzelal','Crueldad',1),
	('Etz’ab’a’l','Juguete',1), 
	('Etz’ab’alil','Figuras',1),
	('Etz’achak','Dinámica (animación)',1), 
	('Etz’amaq’em','Juegos olímpicos',1), 
	('Etz’amb’äl','Cancha',1),
	('Etz’anch’ekoj','Lotería',1), 
	('Etz’anem','Juego',1),
	('Etz’anem uxlanb’äl, oxlane','Recreo, juego, descanso',1), 
	('Etz’anem, etz’anik','Jugar',1),
	('Etz’anib’äl, kikb’äl','Estadio',1), 
	('Etz’k’yaqb’äl','Tiro al blanco',1), 
	('Ewanik, ewanem','Esconder',1),
	('Eye’m k’aslemal','Esperanza de vida ',1),
	('Eyenik','Esperar',1),
	('Eyowal','Enojo, cólera',1),
	('Ib’och’','Vena, nervios',1),
	('Ib’och’ k’amatyo’jil','Tejido nervioso',1), 
	('Ib’och’il b’oq’och','Nervio óptico',1), 
	('Ib’och’il xikin','Nervio auditivo',1),
	('Ib’oy','Armadillo',1),
	('Ichaj','Verduras, hierba',1), 
	('Ichajb’äl , xoral tikb’al ichaj','Hortaliza',1),
	('Ij','Sarampión',1), 
	('Ija’','Semilla',1), 
	('Ija’b’äl','Semillero',1),
    ('Ija’il','Descendiente',1),
	('Ik','Chile',1),
    ('Ik’','Luna, mes',1), 
	('Ik’ilal','Mensualidad',1),
	('Ikaj','Hacha',1),
    ('Ikan, ixpak’pan','Gallina ciega',1),
	('Ikaq’','Sobrino',1),
	('Ikim, Chuxe’','Abajo de',1),
    ('Ikiranik, ikiranem','Cargar (en la cabeza)',1),
	('Ikoq’ij','Venus',1),
    ('Ikox','Hongo',1),
    ('Ilb’al','Vista',1),
    ('Ilb’äl ch’akul','Radiografía',1),
	('Ilb’äl ij','Retrovisor',1),
	('Ilb’äl näj','Larga vista',1),
    ('Ilb’an','Acto (de la obra)',1),
    ('Ilb’anem','Actuación',1), 
	('Ilb’anik','Actuar',1),
    ('Ilik','Mirar',1),
    ('Ilinem','Responsabilidad',1),
	('Ilk’asnak’','Microscópico',1),
	('Ilk’olb’äl','Teatro (lugar)',1),
	('Ilom','Visto',1),
    ('Ilonb’äl chak','Administración',1),
	('Ilonel','Contralor',1),
	('Ilonel chak','Administrador',1),
	('Ilonem, ilonik','Ver',1),
    ('Iltz’ib’','Monitor (de computador)',1),
	('Ilwäch, lemwäch','Lentes (para ver mejor)',1),
	('Imam','Nieto (a)',1),
    ('Imu’t','Hierbamora, quilete',1),
    ('Imul','Conejo',1),
    ('In','Yo',1), 
    ('Inkane’y, ankane’y','Banano',1),
    ('Inoch’','Sombra (persona o animal)',1), 
	('Inup','Ceiba',1),
	('Iq’, uk’u’xal kaqiq’','Oxígeno',1), 
	('Iq’anem','Oxigenación',1), 
	('Is','Camote',1), 
	('Isab’al','Izabal',1), 
	('Ismachi’','Barba, bigote',1),
	('Ismal','Pluma, pelo de animal',1),
	('Itz','Brujería',1),
	('Itzel','Demonio, diablo, maldad',1), 
	('Itzel kunab’al','Veneno',1),
	('Itzelal','Maldición',1), 
	('Iwir','Ayer',1),
	('Ix','Vosotros',1), 
	('Ixajyuq’','Monja',1),
	('Ixal chak','Trabajo juvenil',1), 
	('Ixatz’yaqb’äl','Blusa',1),
	('Ixija’','Óvulo',1), 
	('Ixija’b’äl','Ovario',1), 
	('Ixim','Maíz',1), 
	('Ixjut','Gusano',1),
	('Ixk’aq','Garra de animal',1), 
	('Ixk’aqaj','Uña',1),
	('Ixkanul, xkanul','Volcán, colina cerro',1), 
	('Ixkolob’','Intestino',1),
	('Ixmatuq’','Tepocate',1), 
	('Ixmukur','Tortolito',1),
	('Ixnam','Cuñada de hombre',1), 
	('Ixoq','Mujer',1),
	('Ixöq k’ulajil','Lesbiana',1), 
	('Ixöq kär','Sirena',1),
	('Ixoqal','Femenino (género)',1),
	('Ixoqil, wixoqil','Esposa',1), 
	('Ixpa’ch','Lagartija',1), 
	('Ixpeq','Sapo',1), 
	('Ixq’alel','Princesa',1),
	('Ixtunäy','Trompa de Falopio',1),
	('Ixtuq’, ixtutz’, ixt’o’r','Rana, renacuajo, tepocate, Ixtuxil	Talón, carcañal',1),
	('Iya','Pericón Iyonem	Obstetricia',1),
	('I’om re','Suegros de hombre',1),
	('Jab’unem, jab’unik', 'Espejo', 2),
	('Jach', 'Perro', 2),
	('Jachak’, jachak’ij', 'Guardián', 2),
	('Jaläq’, jaläq’ij', 'Músico', 2),
	('Jalb’äl', 'Jardín', 2),
	('Jalib’äl', 'Templo', 2),
	('Jan', 'Sol', 2),
	('Janal', 'Día', 2),
	('Jinam', 'Lago', 2),
	('Job’', 'Luz', 2),
	('Job’ k’olib’äl', 'Electricidad', 2),
	('Jolom', 'Tierra', 2),
	('Jolom k’i’k’, ch’uti’, maltyox', 'Planeta', 2),
	('Juyu’, juyub’al', 'Isla', 2),
	('Kamik', 'Fuego', 2),
	('Kanab’äl', 'Bosque', 2),
	('Kaqchikel', 'Idioma', 2),
	('K’aq’ik’', 'Pájaro', 2),
	('K’aslemal', 'Tesoro', 2),
	('K’atb’äl', 'Piedra', 2),
	('K’iche’', 'Pueblo', 2),
	('K’oqa’, k’oqab’al', 'Nube', 2),
	('K’umatz', 'Serpiente', 2),
	('K’utu’', 'Cuchillo', 2),
	('Lab’äl', 'Flor', 2),
	('Lajuj', 'Gato', 2),
	('Lajuj k’utu’, ulew', 'León', 2),
	('Lajuj pusaq', 'Tigre', 2),
	('Lak’ab', 'Estrella',2),
	('Lajuj chik’, tijox', 'Mariposa', 2),
	('Lajuj kaq’, ixim', 'Abeja', 2),
	('Lak’ta’, lak’ta’ b’i’', 'Aire', 2),
	('Lal', 'Agua', 2),
	('Lal k’utu’, iktan', 'Tiburón', 2),
	('Lal ik’, q’anil', 'Pez', 2),
	('Lal tijox', 'Delfín', 2),
	('Lal qanil', 'Ballena', 2),
	('Lal taq’, lal taq’al', 'Río', 2),
	('Lalun', 'Lluvia', 2),
	('Lalun ixim', 'Arco iris', 2),
	('Lalun k’i’k’', 'Tormenta', 2),
	('Lamaj', 'Nieve', 2),
	('Lamaj ilb’al', 'Pico de montaña', 2),
	('Lamaj k’utu’', 'Avalancha', 2),
	('Lamaj taq’al', 'Glaciar', 2),
	('Lamaj tijox', 'Trineo', 2),
	('Lamaj kaq’', 'Esquí', 2),
	('Lamaj chik’, lamaj ixim', 'Copos de nieve', 2),
	('Lamaj k’i’k’', 'Granizo', 2),
	('Lamaj k’an', 'Hielo', 2),
	('Lamaj paq’', 'Ventisca', 2),
	('Lamaj ixim', 'Frío', 2),
	('Lamaj k’aq’ik’', 'Viento', 2),
	('Lamaj lak’ta’', 'Nube de nieve', 2),
	('Lamaj lak’al', 'Tormenta de nieve', 2),
	('Lamaj ak’alb’äl', 'Invierno', 2),
	('Lamaj kumatz', 'Avalancha de nieve', 2),
	('Lamaj sutb’inb’äl', 'Pista de esquí', 2),
	('Lamaj juyu’, lamaj juyub’al', 'Isla de hielo', 2),
	('Lamaj k’aq’, lamaj k’aq’ab’al', 'Bosque de nieve', 2),
	('Lamaj kaqchikel', 'Idioma de nieve', 2),
	('Lamaj k’oqa’, lamaj k’oqab’al', 'Nube de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak’ab', 'Estrella de nieve', 2),
	('Lamaj lak’ta’ b’i’', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq’', 'Abeja de nieve', 2),
	('Lamaj taq’', 'Río de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k’i’k’', 'Tormenta de nieve', 2),
	('Lamaj k’umatz', 'Serpiente de nieve', 2),
	('Lamaj k’utu’', 'Cuchillo de nieve', 2),
	('Lamaj lab’äl', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Mach', 'Sombra', 2),
	('Mal', 'Culebra', 2),
	('Man', 'Pavo', 2),
	('Mukul', 'Cerro', 2),
	('Nak’al', 'Ojo', 2),
	('Nawi', 'Sol', 2),
	('Nik’aj', 'Murciélago', 2),
	('Nim', 'Cara', 2),
	('Nimak', 'Río', 2),
	('Nimlaq’, xinäq’, q’u’, k’uxub’', 'Luz', 2),
	('Nimal', 'Diente', 2),
	('Nimja’', 'Tres', 2),
	('Nimja’ k’i’k’', 'Galaxia', 2),
	('Nimja’ lak’ab', 'Estrella de la mañana', 2),
	('Nimja’ k’ak’al', 'Planeta Marte', 2),
	('Nimja’ lak’ta’', 'Sol', 2),
	('Nimja’ juyu’', 'Tierra', 2),
	('Nimja’ tijox', 'Mariposa', 2),
	('Nimja’ ixim', 'Maíz', 2),
	('Nimja’ chik’, nimja’ ch’uti’', 'Mariposa', 2),
	('Nimja’ kaq’, nimja’ ixim', 'Abeja', 2),
	('Nimja’ paq’', 'Huevo', 2),
	('Nimja’ ik', 'Pescado', 2),
	('Nimja’ kaq’ab’al', 'Murciélago', 2),
	('Nimja’ lamaj', 'Nieve', 2),
	('Nimja’ lak’ab', 'Estrella de la tarde', 2),
	('Nimja’ lak’ta’ b’i’', 'Viento', 2),
	('Nimja’ lal', 'Agua', 2),
	('Nimja’ tijox', 'Mariposa de noche', 2),
	('Nimja’ kaq’', 'Abeja de noche', 2),
	('Nimja’ taq’', 'Río de noche', 2),
	('Nimja’ lamajun', 'Lluvia de noche', 2),
	('Nimja’ ixim', 'Arco iris de noche', 2),
	('Nimja’ k’i’k’', 'Tormenta de noche', 2),
	('Nimja’ k’umatz', 'Serpiente de noche', 2),
	('Nimja’ k’utu’', 'Cuchillo de noche', 2),
	('Nimja’ lab’äl', 'Flor de noche', 2),
	('Nimja’ lajuj', 'Gato de noche', 2),
	('Nimja’ lak’ab', 'Estrella de noche', 2),
	('Nimja’ lak’ta’ b’i’', 'Aire de noche', 2),
	('Nimja’ lal', 'Agua de noche', 2),
	('Machik', 'Oscuridad', 2),
    ('Mutz’, mutz’ij', 'Cosecha', 2),
    ('Muk’ul', 'Montaña', 2),
    ('Muk’ul nimak', 'Río de montaña', 2),
    ('Muk’ul lak’ab', 'Estrella de montaña', 2),
    ('Muk’ul tijox', 'Mariposa de montaña', 2),
    ('Muk’ul ixim', 'Maíz de montaña', 2),
    ('Muk’ul chik’, muk’ul ch’uti’', 'Mariposa de montaña', 2),
    ('Muk’ul kaq’, muk’ul ixim', 'Abeja de montaña', 2),
    ('Muk’ul paq’', 'Huevo de montaña', 2),
    ('Muk’ul ik’', 'Pescado de montaña', 2),
    ('Muk’ul kaq’ab’al', 'Murciélago de montaña', 2),
    ('Muk’ul lamaj', 'Nieve de montaña', 2),
    ('Muk’ul lak’ta’ b’i’', 'Viento de montaña', 2),
    ('Muk’ul lal', 'Agua de montaña', 2),
    ('Muk’ul tijox', 'Mariposa de montaña', 2),
    ('Muk’ul taq’', 'Río de montaña', 2),
    ('Muk’ul lamajun', 'Lluvia de montaña', 2),
    ('Muk’ul ixim', 'Arco iris de montaña', 2),
    ('Muk’ul k’i’k’', 'Tormenta de montaña', 2),
    ('Muk’ul k’umatz', 'Serpiente de montaña', 2),
    ('Muk’ul k’utu’', 'Cuchillo de montaña', 2),
    ('Muk’ul lab’äl', 'Flor de montaña', 2),
    ('Muk’ul lajuj', 'Gato de montaña', 2),
    ('Muk’ul lak’ab', 'Estrella de montaña', 2),
    ('Muk’ul lak’ta’ b’i’', 'Aire de montaña', 2),
    ('Muk’ul lal', 'Agua de montaña', 2),
	('Oq’, oq’ij', 'Luz', 2), 
    ('Oq’ab’, oq’ab’al', 'Sombra', 2),
    ('Oq’al', 'Culebra', 2),
    ('Oq’ijal', 'Diente de león', 2),
    ('Oq’ij k’utu’', 'Cuchillo de luz', 2),
    ('Oq’ij tijox', 'Mariposa de luz', 2),
    ('Oq’ij ixim', 'Maíz de luz', 2),
    ('Oq’ij chik’, oq’ij ch’uti’', 'Mariposa de luz', 2),
    ('Oq’ij kaq’, oq’ij ixim', 'Abeja de luz', 2),
    ('Oq’ij paq’', 'Huevo de luz', 2),
    ('Oq’ij ik’', 'Pescado de luz', 2),
    ('Oq’ij kaq’ab’al', 'Murciélago de luz', 2),
    ('Oq’ij lamaj', 'Nieve de luz', 2),
    ('Oq’ij lak’ab', 'Estrella de luz', 2),
    ('Oq’ij lak’ta’ b’i’', 'Viento de luz', 2),
    ('Oq’ij lal', 'Agua de luz', 2),
    ('Oq’ij tijox', 'Mariposa de luz', 2),
    ('Oq’ij taq’', 'Río de luz', 2),
    ('Oq’ij lamajun', 'Lluvia de luz', 2),
    ('Oq’ij ixim', 'Arco iris de luz', 2),
    ('Oq’ij k’i’k’', 'Tormenta de luz', 2),
    ('Oq’ij k’umatz', 'Serpiente de luz', 2),
    ('Oq’ij k’utu’', 'Cuchillo de luz', 2),
    ('Oq’ij lab’äl', 'Flor de luz', 2),
    ('Oq’ij lajuj', 'Gato de luz', 2),
    ('Oq’ij lak’ab', 'Estrella de luz', 2),
    ('Oq’ij lak’ta’ b’i’', 'Aire de luz', 2),
    ('Oq’ij lal', 'Agua de luz', 2),
	('Läch’, lach’ik’, chak, chakäl', 'Niño', 2),
    ('Läch k’utu’, lach’ik k’utu’', 'Cuchillo de niño', 2),
    ('Läch tijox', 'Mariposa de niño', 2),
    ('Läch kaq’, lach’ik ixim', 'Abeja de niño', 2),
    ('Läch paq’', 'Huevo de niño', 2),
    ('Läch ik’', 'Pescado de niño', 2),
    ('Läch kaq’ab’al', 'Murciélago de niño', 2),
    ('Läch lamaj', 'Nieve de niño', 2),
    ('Läch lak’ab', 'Estrella de niño', 2),
    ('Läch lak’ta’ b’i’', 'Viento de niño', 2),
    ('Läch lal', 'Agua de niño', 2),
    ('Läch tijox', 'Mariposa de niño', 2),
    ('Läch taq’', 'Río de niño', 2),  
	('Läch lamajun', 'Lluvia de niño', 2),
    ('Läch ixim', 'Arco iris de niño', 2),
    ('Läch k’i’k’', 'Tormenta de niño', 2),
    ('Läch k’umatz', 'Serpiente de niño', 2),
    ('Läch k’utu’', 'Cuchillo de niño', 2),
    ('Läch lab’äl', 'Flor de niño', 2),
    ('Läch lajuj', 'Gato de niño', 2),
    ('Läch lak’ab', 'Estrella de niño', 2),
    ('Läch lak’ta’ b’i’', 'Aire de niño', 2),
    ('Läch lal', 'Agua de niño', 2),
    ('Lächun', 'Lluvia de niño', 2),
    ('Läch ixim', 'Arco iris de niño', 2),
    ('Läch k’i’k’', 'Tormenta de niño', 2),
    ('Läch k’umatz', 'Serpiente de niño', 2),
    ('Läch k’utu’', 'Cuchillo de niño', 2),
    ('Läch lab’äl', 'Flor de niño', 2),
    ('Läch lajuj', 'Gato de niño', 2),
    ('Läch lak’ab', 'Estrella de niño', 2),
    ('Läch lak’ta’ b’i’', 'Aire de niño', 2),
    ('Läch lal', 'Agua de niño', 2),
	('Päwä', 'Luz', 2),
    ('Paxil', 'Sombra', 2),
    ('Pech', 'Perro', 2),
    ('Pechak’, pechak’ij', 'Guardián', 2),
    ('Pel', 'Músico', 2),
    ('Pelb’äl', 'Jardín', 2),
    ('Pelib’äl', 'Templo', 2),
    ('Pen', 'Sol', 2),
    ('Penal', 'Día', 2),
    ('Pij', 'Lago', 2),
    ('Pob’', 'Luz', 2),
    ('Pob’ k’olib’äl', 'Electricidad', 2),
    ('Polom', 'Tierra', 2),
    ('Polom k’i’k’, ch’uti’, maltyox', 'Planeta', 2),
    ('Puyu’, puyub’al', 'Isla', 2),
    ('Pamik', 'Fuego', 2),
    ('Panab’äl', 'Bosque', 2),
    ('Paqchikel', 'Idioma', 2),
    ('P’aq’ik’', 'Pájaro', 2),
    ('P’aslemal', 'Tesoro', 2),
    ('P’atb’äl', 'Piedra', 2),
    ('P’iche’', 'Pueblo', 2),
    ('P’oqa’, p’oqab’al', 'Nube', 2),
    ('P’umatz', 'Serpiente', 2),
    ('P’utu’', 'Cuchillo', 2),
    ('P’ab’äl', 'Flor', 2),
    ('P’ajuj', 'Gato', 2),
    ('P’ajuj k’utu’, ulew', 'León', 2),
    ('P’ajuj pusaq', 'Tigre', 2),
    ('P’ak’ab', 'Estrella', 2),
    ('P’ajuj chik’, tijox', 'Mariposa', 2),
    ('P’ajuj kaq’, ixim', 'Abeja', 2),
    ('P’ak’ta’, p’ak’ta’ b’i’', 'Aire', 2),
    ('Pal', 'Agua', 2),
    ('Pal k’utu’, iktan', 'Tiburón', 2),
    ('Pal ik’, q’anil', 'Pez', 2),
    ('Pal tijox', 'Delfín', 2),
    ('Pal qanil', 'Ballena', 2),
    ('Pal taq’, pal taq’al', 'Río', 2),
    ('Palun', 'Lluvia', 2),
    ('Palun ixim', 'Arco iris', 2),
    ('Palun k’i’k’', 'Tormenta', 2),
    ('Pamaj', 'Nieve', 2),
    ('Pamaj ilb’al', 'Pico de montaña', 2),
    ('Pamaj k’utu’', 'Avalancha', 2),
    ('Pamaj taq’al', 'Glaciar', 2),
    ('Pamaj tijox', 'Trineo', 2),
    ('Pamaj kaq’', 'Esquí', 2),
    ('Pamaj chik’, pamaj ixim', 'Copos de nieve', 2),
    ('Pamaj k’i’k’', 'Granizo', 2),
    ('Pamaj k’an', 'Hielo', 2),
    ('Pamaj paq’', 'Ventisca', 2),
    ('Pamaj ixim', 'Frío', 2),
    ('Pamaj k’aq’ik’', 'Viento', 2),
    ('Pamaj lak’ta’', 'Nube de nieve', 2),
    ('Pamaj lak’al', 'Tormenta de nieve', 2),
    ('Pamaj ak’alb’äl', 'Invierno', 2),
    ('Pamaj kumatz', 'Avalancha de nieve', 2),
    ('Pamaj sutb’inb’äl', 'Pista de esquí', 2),
    ('Pamaj juyu’, pamaj juyub’al', 'Isla de hielo', 2),
    ('Pamaj k’aq’, pamaj k’aq’ab’al', 'Bosque de nieve', 2),
    ('Pamaj kaqchikel', 'Idioma de nieve', 2),
    ('Pamaj k’oqa’, pamaj k’oqab’al', 'Nube de nieve', 2),
    ('Pamaj k’utu’', 'Cuchillo de nieve', 2),
    ('Pamaj lab’äl', 'Flor de nieve', 2),
    ('Pamaj lajuj', 'Gato de nieve', 2),
    ('Pamaj lak’ab', 'Estrella de nieve', 2),
    ('Pamaj lak’ta’ b’i’', 'Aire de nieve', 2),
    ('Pamaj lal', 'Agua de nieve', 2),
    ('Pamaj tijox', 'Mariposa de nieve', 2),
    ('Pamaj kaq’', 'Abeja de nieve', 2),
    ('Pamaj taq’', 'Río de nieve', 2),
    ('Pamaj pamajun', 'Lluvia de nieve', 2),
    ('Pamaj ixim', 'Arco iris de nieve', 2),
    ('Pamaj k’i’k’', 'Tormenta de nieve', 2),
    ('Pamaj k’umatz', 'Serpiente de nieve', 2),
    ('Pamaj k’utu’', 'Cuchillo de nieve', 2),
    ('Pamaj lab’äl', 'Flor de nieve', 2),
    ('Pamaj lajuj', 'Gato de nieve', 2),
    ('Pamaj lak’ab', 'Estrella de nieve', 2),
    ('Pamaj lak’ta’ b’i’', 'Aire de nieve', 2),
    ('Pamaj lal', 'Agua de nieve', 2),
	('Qäch’, qach’ik’, chak, chakäl', 'Niño', 2),
    ('Qäch k’utu’, qach’ik k’utu’', 'Cuchillo de niño', 2),
    ('Qäch tijox', 'Mariposa de niño', 2),
    ('Qäch kaq’, qach’ik ixim', 'Abeja de niño', 2),
    ('Qäch paq’', 'Huevo de niño', 2),
    ('Qäch ik’', 'Pescado de niño', 2),
    ('Qäch kaq’ab’al', 'Murciélago de niño', 2),
    ('Qäch lamaj', 'Nieve de niño', 2),
    ('Qäch lak’ab', 'Estrella de niño', 2),
    ('Qäch lak’ta’ b’i’', 'Viento de niño', 2),
    ('Qäch lal', 'Agua de niño', 2),
    ('Qäch tijox', 'Mariposa de niño', 2),
    ('Qäch taq’', 'Río de niño', 2),
    ('Qäch lamajun', 'Lluvia de niño', 2),
    ('Qäch ixim', 'Arco iris de niño', 2),
    ('Qäch k’i’k’', 'Tormenta de niño', 2),
    ('Qäch k’umatz', 'Serpiente de niño', 2),
    ('Qäch k’utu’', 'Cuchillo de niño', 2),
    ('Qäch lab’äl', 'Flor de niño', 2),
    ('Qäch lajuj', 'Gato de niño', 2),
    ('Qäch lak’ab', 'Estrella de niño', 2),
    ('Qäch lak’ta’ b’i’', 'Aire de niño', 2),
    ('Qäch lal', 'Agua de niño', 2),
    ('Qächun', 'Lluvia de niño', 2),
    ('Qäch ixim', 'Arco iris de niño', 2),
    ('Qäch k’i’k’', 'Tormenta de niño', 2),
    ('Qäch k’umatz', 'Serpiente de niño', 2),
    ('Qäch k’utu’', 'Cuchillo de niño', 2),
    ('Qäch lab’äl', 'Flor de niño', 2),
    ('Qäch lajuj', 'Gato de niño', 2),
    ('Qäch lak’ab', 'Estrella de niño', 2),
    ('Qäch lak’ta’ b’i’', 'Aire de niño', 2),
    ('Qäch lal', 'Agua de niño', 2),
	('Räwä', 'Luz', 2),
    ('Raxil', 'Sombra', 2),
    ('Rech', 'Perro', 2),
    ('Rechak’, rechak’ij', 'Guardián', 2),
    ('Rel', 'Músico', 2),
    ('Relb’äl', 'Jardín', 2),
    ('Relib’äl', 'Templo', 2),
    ('Ren', 'Sol', 2),
    ('Renal', 'Día', 2),
    ('Rij', 'Lago', 2),
    ('Rob’', 'Luz', 2),
    ('Rob’ k’olib’äl', 'Electricidad', 2),
    ('Rolom', 'Tierra', 2),
    ('Rolom k’i’k’, ch’uti’, maltyox', 'Planeta', 2),
    ('Ruyu’, ruyub’al', 'Isla', 2),
    ('Ramik', 'Fuego', 2),
    ('Ranab’äl', 'Bosque', 2),
    ('Raqchikel', 'Idioma', 2),
    ('R’aq’ik’', 'Pájaro', 2),
    ('R’aslemal', 'Tesoro', 2),
    ('R’atb’äl', 'Piedra', 2),
    ('R’iche’', 'Pueblo', 2),
    ('R’oqa’, r’oqab’al', 'Nube', 2),
    ('R’umatz', 'Serpiente', 2),
    ('R’utu’', 'Cuchillo', 2),
    ('R’ab’äl', 'Flor', 2),
    ('R’ajuj', 'Gato', 2),
    ('R’ajuj k’utu’, ulew', 'León', 2),
    ('R’ajuj pusaq', 'Tigre', 2),
    ('R’ak’ab', 'Estrella', 2),
    ('R’ajuj chik’, tijox', 'Mariposa', 2),
    ('R’ajuj kaq’, ixim', 'Abeja', 2),
    ('R’ak’ta’, r’ak’ta’ b’i’', 'Aire', 2),
    ('Ral', 'Agua', 2),
    ('Ral k’utu’, iktan', 'Tiburón', 2),
    ('Ral ik’, q’anil', 'Pez', 2),
    ('Ral tijox', 'Delfín', 2),
    ('Ral qanil', 'Ballena', 2),
    ('Ral taq’, ral taq’al', 'Río', 2),-
    ('Ralun', 'Lluvia', 2),
    ('Ralun ixim', 'Arco iris', 2),
    ('Ralun k’i’k’', 'Tormenta', 2),
    ('Ramaj', 'Nieve', 2),
    ('Ramaj ilb’al', 'Pico de montaña', 2),
    ('Ramaj k’utu’', 'Avalancha', 2),
    ('Ramaj taq’al', 'Glaciar', 2),
    ('Ramaj tijox', 'Trineo', 2),
    ('Ramaj kaq’', 'Esquí', 2),
    ('Ramaj chik’, ramaj ixim', 'Copos de nieve', 2),
    ('Ramaj k’i’k’', 'Granizo', 2),
    ('Ramaj k’an', 'Hielo', 2),
    ('Ramaj paq’', 'Ventisca', 2),
    ('Ramaj ixim', 'Frío', 2),
    ('Ramaj k’aq’ik’', 'Viento', 2),
    ('Ramaj lak’ta’', 'Nube de nieve', 2),
    ('Ramaj lak’al', 'Tormenta de nieve', 2),
    ('Ramaj ak’alb’äl', 'Invierno', 2),
    ('Ramaj kumatz', 'Avalancha de nieve', 2),
    ('Ramaj sutb’inb’äl', 'Pista de esquí', 2),
    ('Ramaj juyu’, ramaj juyub’al', 'Isla de hielo', 2),
    ('Ramaj k’aq’, ramaj k’aq’ab’al', 'Bosque de nieve', 2),
    ('Ramaj kaqchikel', 'Idioma de nieve', 2),
    ('Ramaj k’oqa’, ramaj k’oqab’al', 'Nube de nieve', 2),
    ('Ramaj k’utu’', 'Cuchillo de nieve', 2),
    ('Ramaj lab’äl', 'Flor de nieve', 2),
    ('Ramaj lajuj', 'Gato de nieve', 2),
    ('Ramaj lak’ab', 'Estrella de nieve', 2),
    ('Ramaj lak’ta’ b’i’', 'Aire de nieve', 2),
    ('Ramaj lal', 'Agua de nieve', 2),
    ('Ramaj tijox', 'Mariposa de nieve', 2),
    ('Ramaj kaq’', 'Abeja de nieve', 2),
    ('Ramaj taq’', 'Río de nieve', 2),
    ('Ramaj ramajun', 'Lluvia de nieve', 2),
    ('Ramaj ixim', 'Arco iris de nieve', 2),
    ('Ramaj k’i’k’', 'Tormenta de nieve', 2),
    ('Ramaj k’umatz', 'Serpiente de nieve', 2),
    ('Ramaj k’utu’', 'Cuchillo de nieve', 2),
    ('Ramaj lab’äl', 'Flor de nieve', 2),
    ('Ramaj lajuj', 'Gato de nieve', 2),
    ('Ramaj lak’ab', 'Estrella de nieve', 2),
    ('Ramaj lak’ta’ b’i’', 'Aire de nieve', 2),
    ('Ramaj lal', 'Agua de nieve', 2),
	('Säwä', 'Luz', 2),
    ('Saxil', 'Sombra', 2),
    ('Sech', 'Perro', 2),
    ('Sechak’, sechak’ij', 'Guardián', 2),
    ('Sel', 'Músico', 2),
    ('Selb’äl', 'Jardín', 2),
    ('Selib’äl', 'Templo', 2),
    ('Sen', 'Sol', 2),
    ('Senal', 'Día', 2),
    ('Sij', 'Lago', 2),
    ('Sob’', 'Luz', 2),
    ('Sob’ k’olib’äl', 'Electricidad', 2),
    ('Solom', 'Tierra', 2),
    ('Solom k’i’k’, ch’uti’, maltyox', 'Planeta', 2),
    ('Suyu’, suyub’al', 'Isla', 2),
    ('Samik', 'Fuego', 2),
    ('Sanab’äl', 'Bosque', 2),
    ('Saqchikel', 'Idioma', 2),
    ('S’aq’ik’', 'Pájaro', 2),
    ('S’aslemal', 'Tesoro', 2),
    ('S’atb’äl', 'Piedra', 2),
    ('S’iche’', 'Pueblo', 2),
    ('S’oqa’, s’oqab’al', 'Nube', 2),
    ('S’umatz', 'Serpiente', 2),
    ('S’utu’', 'Cuchillo', 2),
    ('S’ab’äl', 'Flor', 2),
    ('S’ajuj', 'Gato', 2),
    ('S’ajuj k’utu’, ulew', 'León', 2),
    ('S’ajuj pusaq', 'Tigre', 2),
    ('S’ak’ab', 'Estrella', 2),
    ('S’ajuj chik’, tijox', 'Mariposa', 2),
    ('S’ajuj kaq’, ixim', 'Abeja', 2),
    ('S’ak’ta’, s’ak’ta’ b’i’', 'Aire', 2),
    ('Sal', 'Agua', 2),
    ('Sal k’utu’, iktan', 'Tiburón', 2),
    ('Sal ik’, q’anil', 'Pez', 2),
    ('Sal tijox', 'Delfín', 2),
    ('Sal qanil', 'Ballena', 2),
    ('Sal taq’, sal taq’al', 'Río', 2),
    ('Salun', 'Lluvia', 2),
    ('Salun ixim', 'Arco iris', 2),
    ('Salun k’i’k’', 'Tormenta', 2),
    ('Samaj', 'Nieve', 2),
    ('Samaj ilb’al', 'Pico de montaña', 2),
    ('Samaj k’utu’', 'Avalancha', 2),
    ('Samaj taq’al', 'Glaciar', 2),
    ('Samaj tijox', 'Trineo', 2),
    ('Samaj kaq’', 'Esquí', 2),
    ('Samaj chik’, samaj ixim', 'Copos de nieve', 2),
    ('Samaj k’i’k’', 'Granizo', 2),
    ('Samaj k’an', 'Hielo', 2),
    ('Samaj paq’', 'Ventisca', 2),
    ('Samaj ixim', 'Frío', 2),
    ('Samaj k’aq’ik’', 'Viento', 2),
    ('Samaj lak’ta’', 'Nube de nieve', 2),
    ('Samaj lak’al', 'Tormenta de nieve', 2),
    ('Samaj ak’alb’äl', 'Invierno', 2),
    ('Samaj kumatz', 'Avalancha de nieve', 2),
    ('Samaj sutb’inb’äl', 'Pista de esquí', 2),
    ('Samaj juyu’, samaj juyub’al', 'Isla de hielo', 2),
    ('Samaj k’aq’, samaj k’aq’ab’al', 'Bosque de nieve', 2),
    ('Samaj kaqchikel', 'Idioma de nieve', 2),
    ('Samaj k’oqa’, samaj k’oqab’al', 'Nube de nieve', 2),
    ('Samaj k’utu’', 'Cuchillo de nieve', 2),
    ('Samaj lab’äl', 'Flor de nieve', 2),
    ('Samaj lajuj', 'Gato de nieve', 2),
    ('Samaj lak’ab', 'Estrella de nieve', 2),
    ('Samaj lak’ta’ b’i’', 'Aire de nieve', 2),
    ('Samaj lal', 'Agua de nieve', 2),
	('Taqal', 'Tierra', 2),
	('Tz’utujil', 'Idioma', 2),
	('Tz’utujil jaqal', 'Territorio', 2),
	('Tz’utujil xonaqal', 'País', 2),
	('Ub’anik', 'Enseñar', 2),
	('Uk’itunem', 'Romper', 2),
	('Ulew', 'Cielo', 2),
	('Ulew winaq', 'Estrella', 2),
	('Taq', 'Piedra', 2),
	('Taqab’, taq’, taqatz’, tzuktz’, tz’i’, tzak’ik’, tzakal', 'Animales', 2),
	('Tz’a’, tz’it’, tz’ik’ab’, tz’ununij', 'Insectos', 2),
	('Tz’aq', 'Culebra', 2),
	('Tz’aqon', 'Serpiente', 2),
	('Tz’ikin', 'Pájaro', 2),
	('Tz’ikin jaqal', 'Nido', 2),
	('Tz’oq', 'Buitre', 2),
	('Tz’ut', 'Lengua', 2),
	('Tz’utujil winaq', 'Persona', 2),
	('Tz’utujil q’anil', 'Comunidad', 2)
	('Tz’utujil ajaw', 'Líder', 2),
	('Tz’utujil tzikin', 'Ave', 2),
	('Tz’utujil winaq tz’a’, tz’i’, tzak’ik’, tzakal', 'Gente de la Tierra', 2),
	('Tz’ununij', 'Mariposa', 2),
	('Tz’ununij jaqal', 'Jardín', 2),
	('Tz’ununij winaq', 'Mariposero', 2),
	('Tz’ununij tz’i’, tzak’ik’', 'Polilla', 2),
	('Tz’ununij tzikin', 'Mariposa nocturna', 2),
	('Tz’ununij tzakal', 'Mariposa diurna', 2),
	('Tz’ununij winaq tz’a’', 'Observador de mariposas', 2),
	('Tz’ununij q’umarkaj', 'Mariposa monarca', 2),
	('Tz’ununij winaq tz’a’ tz’i’', 'Lepidopterista', 2),
	('Tz’ununij winaq tz’a’ tzakal', 'Entomólogo', 2),
	('Tz’ununij ajaw', 'Mariposa reina', 2),
	('Tz’ununij ajaw tzikin', 'Mariposa monarca', 2),
	('Tz’ununij ajaw tzakal', 'Mariposa reina', 2),
	('Tz’ununij ajaw winaq tz’a’ tz’i’', 'Entomóloga', 2),
	('Tz’ununij ajaw winaq tz’a’ tzakal', 'Amante de las mariposas', 2),
	('Tz’ununij ajaw tz’a’', 'Naturaleza', 2),
	('Tz’ununij ajaw tz’a’ tz’i’, tzak’ik’', 'Ecosistema', 2),
	('Tz’ununij ajaw tz’a’ tzikin', 'Biodiversidad', 2),
	('Tz’ununij ajaw tz’a’ tzakal', 'Conservación', 2),
	('Tz’ununij ajaw winaq tz’a’ tz’i’, tzak’ik’', 'Sostenibilidad', 2),
	('Tz’ununij ajaw winaq tz’a’ tzakal', 'Ecología', 2),
	('Tz’ununij ajaw winaq tz’a’ tzakal', 'Preservación', 2),
	('Tz’ununij ajaw winaq tz’a’ tzikin', 'Restauración', 2),
	('Tz’ununij ajaw winaq tz’a’ tz’i’', 'Educación ambiental', 2),
	('Tz’ununij ajaw winaq tz’a’ tzak’ik’', 'Cuidado del medio ambiente', 2),
	('Tz’ununij ajaw winaq tz’a’ tz’i’', 'Conciencia ambiental', 2),
	('Tz’ununij ajaw winaq tz’a’ tzakal', 'Reciclaje', 2),
	('Tz’ununij ajaw winaq tz’a’ tzakal', 'Sustentabilidad', 2),
	('U', 'Agua', 2),
	('Ub’anel', 'Despierto', 2),
	('Uk’u’, uk’u’aj', 'Romper', 2),
	('Uk’ub’, uk’ub’aj', 'Erosionar', 2),
	('Uk’ul', 'Saltar', 2),
	('Uk’ut, uk’utaj', 'Volar', 2),
	('Uk’utem', 'Flotar', 2),
	('Uk’ux, uk’uxaj', 'Hundir', 2),
	('Uk’uy, uk’uyaj', 'Moler', 2),
	('Uk’uyem', 'Masticar', 2),
	('Ul, ulaj', 'Ver', 2),
	('Ul’u’, ul’u’aj', 'Soñar', 2),
	('Ulej', 'Mirar', 2),
	('Ulem', 'Observar', 2),
	('Ulub’, ulub’aj', 'Esconder', 2),
	('Uluw, uluwaj', 'Reír', 2),
	('Umuq, umuqaj', 'Ladrar', 2),
	('Unen', 'Oler', 2),
	('Uq’, uq’aj', 'Escuchar', 2),
	('Uq’ub’, uq’ub’aj', 'Palpar', 2),
	('Uq’ul', 'Girar', 2),
	('Uq’ut, uq’utaj', 'Empujar', 2),
	('Uq’uy, uq’uyaj', 'Abrir', 2),
	('Uq’uyem', 'Destapar', 2),
	('Ur, uraj', 'Gritar', 2),
	('Urub’, urub’aj', 'Aullar', 2),
	('Ut, utaj', 'Comer', 2),
	('Utem', 'Beber', 2),
	('Utz, utzaj', 'Caminar', 2),
	('Utzuk, utzukaj', 'Andar', 2),
	('Utzul, utzulaj', 'Correr', 2),
	('Utzum, utzumaj', 'Nadar', 2),
	('Utzunem', 'Bailar', 2),
	('Utzut, utzutaj', 'Saltar', 2),
	('Utz’ut, utz’utaj', 'Volar', 2),
	('Utz’utem', 'Flotar', 2),
	('Utz’ux, utz’uxaj', 'Hundir', 2),
	('Utz’uy, utz’uyaj', 'Moler', 2),
	('Utz’uyem', 'Masticar', 2),
	('Ul, ulaj', 'Ver', 2),
	('Ul’u’, ul’u’aj', 'Soñar', 2),
	('Ulej', 'Mirar', 2),
	('Ulem', 'Observar', 2),
	('Ulub’, ulub’aj', 'Esconder', 2),
	('Uluw, uluwaj', 'Reír', 2),
	('Umuq, umuqaj', 'Ladrar', 2),
	('Unen', 'Oler', 2),
	('Uq’, uq’aj', 'Escuchar', 2),
	('Uq’ub’, uq’ub’aj', 'Palpar', 2),
	('Uq’ul', 'Girar', 2),
	('Vak’ab’','Tiembla', 2),
	('Vak’axik’', 'Brilla', 2),
	('Vak’ixik’','Relincha', 2),
	('Vak’oq’','Riñe', 2),
	('Vak’oq’el, vak’oq’em', 'Riéndose', 2),
	('Vak’uq’', 'Ve', 2),
	('Vak’uq’em', 'Viendo', 2),
	('Vak’uxik’', 'Mira', 2),
	('Vak’uyik’', 'Muestra', 2),
	('Vak’ub’aq','Empieza', 2),
	('Vak’alb’äl', 'Entra', 2),
	('Vak’alik’', 'Anuncia', 2),
	('Vak’atz’aj', 'Lee', 2),
	('Vak’ik’aj', 'Escribe', 2),
	('Vak’atz’i’', 'Instruye', 2),
	('Vak’alq’ij', 'Charla', 2),
	('Vak’oqil', 'Explica', 2),
	('Vak’ol', 'Conversa', 2),
	('Vak’oq’', 'Discute', 2),
	('Vak’i’', 'Argumenta', 2),
	('Vak’oraj', 'Debate', 2),
	('Vak’ik’aj', 'Confronta', 2),
	('Vak’ol', 'Negocia', 2),
	('Vak’olq’ij', 'Comparte', 2),
	('Vak’uq’aj', 'Colabora', 2),
	('Vak’utz’aj', 'Coopera', 2),
	('Vak’utaj', 'Ayuda', 2),
	('Vak’uyaj', 'Apoya', 2),
	('Vak’uyem', 'Facilita', 2),
	('Vak’uq’aj', 'Trabaja', 2),
	('Vak’ulaj', 'Resuelve', 2),
	('Vak’ulq’ij', 'Crea', 2),
	('Vak’ulik’aj', 'Innova', 2),
	('Vak’ub’aj', 'Diseña', 2),
	('Vak’ib’al', 'Produce', 2),
	('Vak’ib’alaj', 'Fabrica', 2),
	('Vak’ib’ik’aj', 'Construye', 2),
	('Vak’ib’ulaj', 'Crea', 2),
	('Vak’ib’aq', 'Inicia', 2),
	('Vak’alb’äl', 'Orfanato', 2),
	('Wa’', 'Pasar', 2),
	('Waq', 'Caminar', 2),
	('Waq’ol', 'Mover', 2),
	('Waq’um', 'Volar', 2),
	('Waq’ut', 'Saltar', 2),
	('Waq’uy', 'Correr', 2),
	('Waq’uyem', 'Huir', 2),
	('Waqib’', 'Ayudar', 2),
	('Waqik’aj', 'Guiar', 2),
	('Waqik’em', 'Guiando', 2),
	('Waqik’el', 'Guía', 2),
	('Waqik’oq', 'Guiado', 2),
	('Waqik’oqel', 'Guía', 2),
	('Waqik’um', 'Guiando', 2),
	('Waq’araj', 'Cosecha', 2),
	('Waq’olaj', 'Fuma', 2),
	('Waq’oq', 'Tose', 2),
	('Waq’oq’aj', 'Tos', 2),
	('Waq’oq’el', 'Tos', 2),
	('Waq’oq’oq', 'Tose', 2),
	('Waq’uq’', 'Busca', 2),
	('Waq’uq’aj', 'Búsqueda', 2),
	('Waq’uq’el', 'Búsqueda', 2),
	('Waq’uq’oq', 'Busca', 2),
	('Waq’uxik’', 'Mira', 2),
	('Waq’uyik’', 'Muestra', 2),
	('Waq’uyik’em', 'Mostrando', 2),
	('Waq’uyik’el', 'Muestra', 2),
	('Waq’uyik’oq', 'Muestra', 2),
	('Waq’uyem', 'Muestra', 2),
	('Waq’uyemem', 'Mostrando', 2),
	('Waq’uyel', 'Muestra', 2),
	('Waq’uyoq', 'Muestra', 2),
	('Waq’ub’', 'Diseña', 2),
	('Waq’ub’aj', 'Diseñador', 2),
	('Waq’ub’el', 'Diseño', 2),
	('Waq’ub’oq', 'Diseña', 2),
	('Waq’ub’oqel', 'Diseño', 2),
	('Waq’ub’um', 'Diseñando', 2),
	('Waq’ub’umel', 'Diseñador', 2),
	('Waq’ib’al', 'Produce', 2),
	('Waq’ib’alaj', 'Fabrica', 2),
	('Waq’ib’ik’aj', 'Construye', 2),
	('Waq’ib’ulaj', 'Crea', 2),
	('Waq’ib’aq', 'Inicia', 2),
	('Waq’alb’äl', 'Orfanato', 2),
	('Waq’atz’em', 'Aprende', 2),
	('Waq’atz’emem', 'Aprendiendo', 2),
	('Waq’atz’el', 'Aprender', 2),
	('Waq’atz’oq', 'Aprende', 2),
	('Xa', 'Desvalorativa', 2),
	('Xa chi je wi', 'Siempre es así', 2),
	('Xajab’', 'Caite, zapato', 2),
	('Xajäb’ b’inb’äl', 'Patín, patineta', 2),
	('Xajoj nimachi', 'Gigante (danza)', 2),
	('Xajoj, xojoj', 'Baile, danza', 2),
	('Xak’ab’', 'Brazada', 2),
	('Xalq’at', 'Cruz', 2),
	('Xalq’at b’e', 'Cruce', 2),
	('Xalq’at juch’', 'Coordenadas cartesianas', 2),
	('Xan', 'Adobe, pared', 2),
	('Xan ab’aj', 'Bloc', 2),
	('Xanab’äj', 'Adoquín', 2),
	('Xantz’ajb’äl', 'Acuarela', 2),
	('Xaq', 'Tizne', 2),
	('Xaq k’a te’', 'De repente', 2),
	('Xaq tz’ib’, jujunal tz’ib’', 'Letra de molde', 2),
	('Xaq, uxaq', 'Hoja', 2),
	('Yab’ab’ ch’ich’', 'Amortiguador', 2),
	('Yab’il', 'Enfermedad', 2),
	('Yab’waram', 'Somnolencia', 2),
	('Yab’yoj', 'Discapacitados', 2),
	('Yajo9nem, yajonik', 'Regañar', 2),
	('Yak', 'Gato de monte', 2),
	('Yakal tze’', 'Chistoso, divertido', 2),
	('Yakatajem, yakatajik', 'Levantar', 2),
	('Yakb’äl ch’ich’', 'Trique (para cambiar llantas)', 2),
	('Yaköl tze’', 'Cómico', 2),
	('Ya’al ub’ixik', 'Maestro de ceremonia', 2),
	('Ya’b’äl kaq’iq’', 'Inflador', 2),
	('Ya’b’äl q’aq’', 'Lámpara', 2),
	('Ya’ik uwi’', 'Más', 2),
	('Ya’ik, ya’onem, ya’onik', 'Dar', 2),
	('Ya’ltajkil', 'Procesador', 2),
	('Ya’ltze’', 'Chiste', 2),
	('Ya’ltzijol', 'Campaña “política”', 2),
	('Ya’ltzijolil', 'Publicidad', 2),
	('Ya’talil', 'Derecho', 2),
	('Ya’talil Alaxik', 'Derechos de la Familia', 2),
	('Ya’talil Tinamit', 'Derechos de los Pueblos', 2),
	('Ya’talil Winaqilal', 'Derechos Humanos', 2),
	('Y’oxmin', 'Mitosis', 2);
	








	
	



